CREATE DATABASE IF NOT EXISTS dvd_co;
CREATE USER IF NOT EXISTS 'dvd_co_app'@'localhost' IDENTIFIED BY RANDOM PASSWORD;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES
    ON dvd_co.* TO 'dvd_co_app'@'localhost';